Repository Clariteia/minos_microservice_saga, pull requests merged in 2021-05, with the labels that each got.

#21 #20 (Add `minos.saga.SagaStep`)
  minos/saga/__init__.py
  minos/saga/abstract.py
  minos/saga/local_state.py
  minos/saga/saga.py
  minos/saga/step.py
  minos/saga/step_manager.py
  tests/test_saga/test_saga.py
Labels: enhancement

#29 #26 (migrate to `unittest.TestCase`
  minos/saga/saga.py
  minos/saga/step.py
  minos/saga/step_manager.py
  tests/callbacks.py
  tests/test_saga/test_saga.py
  tests/utils.py
Labels: enhancement

#39 #27 (unique step methods)
  minos/saga/__init__.py
  minos/saga/exceptions.py
  minos/saga/step.py
  tests/test_saga/test_saga.py
  tests/test_saga/test_step.py
Labels: enhancement

#37 #34 (`pre-commit`)
  .pre-commit-config.yaml
  .restyled.yaml
  Makefile
  minos/saga/abstract.py
  minos/saga/step.py
  requirements_dev.txt
  setup.cfg
Labels: enhancement

#41 #23 (create `minos.saga.executions` structure)
  minos/saga/__init__.py
  minos/saga/definitions/__init__.py
  minos/saga/definitions/abc.py
  minos/saga/definitions/saga.py
  minos/saga/definitions/step.py
  minos/saga/exceptions.py
  minos/saga/executions/__init__.py
  minos/saga/executions/context.py
  minos/saga/executions/saga.py
  minos/saga/executions/status.py
  minos/saga/executions/step.py
  minos/saga/saga.py
  minos/saga/step_manager.py
  tests/test_saga/test_definition/__init__.py
  tests/test_saga/test_definition/test_saga.py
  tests/test_saga/test_definition/test_step.py
  tests/test_saga/test_exceptions.py
  tests/test_saga/test_execution/__init__.py
  tests/test_saga/test_execution/test_saga.py
  tests/test_saga/test_execution/test_step.py
  tests/test_saga/test_saga.py
Labels: enhancement

#44 #43 (step manager)
  minos/saga/__init__.py
  minos/saga/definitions/saga.py
  minos/saga/definitions/step.py
  minos/saga/exceptions.py
  minos/saga/executions/__init__.py
  minos/saga/executions/executors/__init__.py
  minos/saga/executions/executors/invoke_participant.py
  minos/saga/executions/executors/local.py
  minos/saga/executions/executors/on_reply.py
  minos/saga/executions/executors/with_compensation.py
  minos/saga/executions/saga.py
  minos/saga/executions/step.py
  minos/saga/local_state.py
  minos/saga/storage.py
  tests/test_saga/test_definitions/__init__.py
  tests/test_saga/test_definitions/test_saga.py
  tests/test_saga/test_definitions/test_step.py
  tests/test_saga/test_exceptions.py
  tests/test_saga/test_executions/__init__.py
  tests/test_saga/test_executions/test_executors/__init__.py
  tests/test_saga/test_executions/test_executors/test_invoke_participant.py
  tests/test_saga/test_executions/test_executors/test_local.py
  tests/test_saga/test_executions/test_executors/test_on_reply.py
  tests/test_saga/test_executions/test_executors/test_with_compensation.py
  tests/test_saga/test_executions/test_saga.py
  tests/test_saga/test_executions/test_step.py
  tests/test_saga/test_storage.py
Labels: enhancement

#49 #48 command preparation callbacks
  minos/saga/__init__.py
  minos/saga/definitions/step.py
  minos/saga/exceptions.py
  minos/saga/executions/__init__.py
  minos/saga/executions/context.py
  minos/saga/executions/executors/__init__.py
  minos/saga/executions/executors/invoke_participant.py
  minos/saga/executions/executors/local.py
  minos/saga/executions/executors/on_reply.py
  minos/saga/executions/executors/publish.py
  minos/saga/executions/executors/with_compensation.py
  minos/saga/executions/saga.py
  minos/saga/executions/status.py
  minos/saga/executions/step.py
  minos/saga/local_state.py
  minos/saga/storage.py
  tests/callbacks.py
  tests/test_saga/test_definitions/test_saga.py
  tests/test_saga/test_definitions/test_step.py
  tests/test_saga/test_exceptions.py
  tests/test_saga/test_executions/test_executors/test_invoke_participant.py
  tests/test_saga/test_executions/test_executors/test_local.py
  tests/test_saga/test_executions/test_executors/test_on_reply.py
  tests/test_saga/test_executions/test_executors/test_with_compensation.py
  tests/test_saga/test_executions/test_saga.py
  tests/test_saga/test_executions/test_step.py
  tests/test_saga/test_local_state.py
  tests/test_saga/test_storage.py
  tests/utils.py
Labels: enhancement

#53 #50 (implement `cls.from_raw` and `obj.raw`)
  minos/saga/__init__.py
  minos/saga/definitions/__init__.py
  minos/saga/definitions/saga.py
  minos/saga/definitions/step.py
  minos/saga/executions/executors/invoke_participant.py
  minos/saga/executions/executors/on_reply.py
  minos/saga/executions/executors/with_compensation.py
  minos/saga/executions/saga.py
  minos/saga/executions/status.py
  minos/saga/executions/step.py
  tests/test_saga/test_definitions/test_saga.py
  tests/test_saga/test_definitions/test_step.py
  tests/test_saga/test_executions/test_saga.py
  tests/test_saga/test_executions/test_status.py
  tests/test_saga/test_executions/test_step.py
Labels: enhancement

#58 #56 (`SagaContext` is serialised in avro keeping constance of types)
  minos/saga/executions/context.py
  minos/saga/executions/saga.py
  minos/saga/executions/step.py
  tests/test_saga/test_executions/test_context.py
  tests/test_saga/test_executions/test_saga.py
  tests/test_saga/test_executions/test_step.py
Labels: enhancement

#61 #42 (review rollback)
  minos/saga/__init__.py
  minos/saga/exceptions.py
  minos/saga/executions/saga.py
  minos/saga/executions/step.py
  tests/test_saga/test_exceptions.py
  tests/test_saga/test_executions/test_saga.py
  tests/test_saga/test_executions/test_step.py
Labels: enhancement

#59 #55 (Integrate with `CommandReply`)
  minos/saga/executions/executors/local.py
  minos/saga/executions/executors/on_reply.py
  minos/saga/executions/saga.py
  minos/saga/executions/step.py
  requirements_dev.txt
  tests/test_saga/test_executions/test_saga.py
  tests/test_saga/test_executions/test_step.py
  tests/utils.py
Labels: enhancement

#62 #46 (store saga execution)
  minos/saga/__init__.py
  minos/saga/exceptions.py
  minos/saga/executions/__init__.py
  minos/saga/executions/saga.py
  minos/saga/executions/storage.py
  minos/saga/local_state.py
  minos/saga/storage.py
  requirements_dev.txt
  tests/test_saga/test_exceptions.py
  tests/test_saga/test_executions/test_saga.py
  tests/test_saga/test_executions/test_storage.py
  tests/test_saga/test_local_state.py
  tests/test_saga/test_storage.py
Labels: enhancement

#63 #28 (docstring)
  minos/saga/__init__.py
  minos/saga/definitions/__init__.py
  minos/saga/definitions/abc.py
  minos/saga/definitions/saga.py
  minos/saga/definitions/step.py
  minos/saga/exceptions.py
  minos/saga/executions/__init__.py
  minos/saga/executions/context.py
  minos/saga/executions/executors/__init__.py
  minos/saga/executions/executors/invoke_participant.py
  minos/saga/executions/executors/local.py
  minos/saga/executions/executors/on_reply.py
  minos/saga/executions/executors/publish.py
  minos/saga/executions/executors/with_compensation.py
  minos/saga/executions/saga.py
  minos/saga/executions/status.py
  minos/saga/executions/step.py
  minos/saga/executions/storage.py
  tests/test_saga/test_definitions/test_saga.py
  tests/test_saga/test_exceptions.py
  tests/test_saga/test_executions/test_executors/test_invoke_participant.py
  tests/test_saga/test_executions/test_executors/test_publish.py
  tests/test_saga/test_executions/test_saga.py
  tests/test_saga/test_executions/test_storage.py
  tests/utils.py
Labels: enhancement, miscellaneous

#65 #64 (update `minos.comon`)
  minos/saga/executions/context.py
  minos/saga/executions/storage.py
  requirements_dev.txt
  tests/test_saga/test_executions/test_storage.py
Labels: miscellaneous

#69 #66 (add `codecov` config)
  codecov.yml
Labels: meta

#78 #77 (flexible version contraints)
  pyproject.toml
Labels: bug

#79 #76 (saga manager)
  minos/saga/__init__.py
  minos/saga/executions/storage.py
  minos/saga/manager.py
  poetry.lock
  tests/config.yml
  tests/order/__init__.py
  tests/order/aggregates.py
  tests/order/services/__init__.py
  tests/order/services/saga.py
  tests/test_saga/test_executions/test_storage.py
  tests/test_saga/test_manager.py
Labels: enhancement

#84 #80 (update `.gitignore`)
  .gitignore
Labels: meta

#83 #81 (inject broker)
  minos/saga/executions/executors/local.py
  minos/saga/executions/executors/publish.py
  minos/saga/executions/saga.py
  minos/saga/manager.py
  poetry.lock
  pyproject.toml
  tests/test_saga/test_executions/test_executors/test_publish.py
  tests/test_saga/test_executions/test_saga.py
  tests/test_saga/test_executions/test_step.py
  tests/test_saga/test_executions/test_storage.py
  tests/test_saga/test_manager.py
  tests/utils.py
Labels: enhancement

#87 #86 (Fix `minos.saga.SagaManager` constructor)
  minos/saga/manager.py
  tests/test_saga/test_manager.py
Labels: bug

#89 #24 (async `minos.saga.SagaExecution.execute` method)
  minos/saga/executions/executors/local.py
  minos/saga/executions/executors/on_reply.py
  minos/saga/executions/executors/publish.py
  minos/saga/executions/saga.py
  minos/saga/executions/step.py
  minos/saga/manager.py
  poetry.lock
  tests/test_saga/test_executions/test_executors/test_local.py
  tests/test_saga/test_executions/test_executors/test_on_reply.py
  tests/test_saga/test_executions/test_executors/test_publish.py
  tests/test_saga/test_executions/test_saga.py
  tests/test_saga/test_executions/test_step.py
  tests/test_saga/test_executions/test_storage.py
  tests/test_saga/test_manager.py
Labels: enhancement

#93 #91 (Pass the `topic` to the broker on `minos.saga.PublishExecutor`)
  minos/saga/executions/executors/publish.py
  tests/test_saga/test_executions/test_executors/test_publish.py
Labels: bug

#104 #100 (update `minos-microservice-common`)
  minos/saga/executions/executors/publish.py
  minos/saga/manager.py
  poetry.lock
  tests/config.yml
  tests/test_saga/test_executions/test_executors/test_publish.py
  tests/test_saga/test_manager.py
  tests/utils.py
Labels: miscellaneous

#107 #106 (Remove warnings)
  Makefile
  setup.cfg
Labels: miscellaneous

#105 #96 (improve exception handling and messages)
  minos/saga/exceptions.py
  minos/saga/executions/executors/on_reply.py
  minos/saga/executions/executors/publish.py
  minos/saga/executions/saga.py
  minos/saga/executions/step.py
  minos/saga/manager.py
  tests/test_saga/test_exceptions.py
  tests/test_saga/test_executions/test_executors/test_publish.py
  tests/test_saga/test_executions/test_saga/test_execute.py
  tests/test_saga/test_executions/test_saga/test_raw.py
  tests/test_saga/test_executions/test_step.py
  tests/test_saga/test_executions/test_storage.py
Labels: enhancement

#102 #101 Documentation
  AUTHORS.md
  CONTRIBUTING.md
  Makefile
  README.md
  RUNTHETESTS.md
  SETUP.md
  docs/authors.rst
  docs/conf.py
  docs/history.rst
  docs/index.rst
  docs/readme.rst
  docs/runthetests.rst
  docs/usage.rst
  poetry.lock
  pyproject.toml
Labels: documentation

#109 #108 ( Fix bug related with `topic_reply`)
  minos/saga/executions/executors/publish.py
  tests/test_saga/test_executions/test_executors/test_publish.py
Labels: bug
